### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by jason89521** [jason89521/react-a11y#6]
## Todo

- [x]  `Space` to activate the button when keyup
- [x]  `Enter` to activate the button when keydown
- [x]  Activate the button when click
- [x]  The button has role of [button](https://w3c.github.io/aria/#button).
- [x]  The button has an accessible label. By default, the accessible name is computed from any text content inside the button element. However, it can also be provided with [aria-labelledby](https://w3c.github.io/aria/#aria-labelledby) or [aria-label](https://w3c.github.io/aria/#aria-label).
- [x]  When the action associated with a button is unavailable, the button has [aria-disabled](https://w3c.github.io/aria/#aria-disabled) set to true.
- [ ]  If activating the button opens a dialog, the focus moves inside the dialog. (see [dialog pattern](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/))
- [ ]  If activating the button closes a dialog, focus typically returns to the button that opened the dialog unless the function performed in the dialog context logically leads to a different element. For example, activating a cancel button in a dialog returns focus to the button that opened the dialog. However, if the dialog were confirming the action of deleting the page from which it was opened, the focus would logically move to a new context.
- [ ]  If activating the button does not dismiss the current context, then focus typically remains on the button after activation, e.g., an Apply or Recalculate button.
- [ ]  If the button action indicates a context change, such as move to next step in a wizard or add another search criteria, then it is often appropriate to move focus to the starting point for that action.
- [ ]  If the button is activated with a shortcut key, the focus usually remains in the context from which the shortcut key was activated. For example, if Alt + U were assigned to an "Up" button that moves the currently focused item in a list one position higher in the list, pressing Alt + U when the focus is in the list would not move the focus from the list.
- [ ] If a description of the button's function is present, the button element has [aria-describedby](https://w3c.github.io/aria/#aria-describedby) set to the ID of the element containing the description.
- [x] If the button is a toggle button, it has an [aria-pressed](https://w3c.github.io/aria/#aria-pressed) state. When the button is toggled on, the value of this state is true, and when toggled off, the state is false.
